export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const POST_CHECKOUT = "POST_CHECKOUT";
