export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
